### PR TITLE
v0.3.0

### LINKED ISSUE #4: [Request] Toggle Options
### Is your suggested enhancement related to a problem? Please describe.

i really love the mod even if it is just some small details, but the thing is that sometimes i just dont want the bubbles to work with some features, like when im fishing

### Describe the solution you'd like

adding a option to toggle on-off in config files

### Describe alternatives you've considered

disabling it
or adding modmenu config

### Additional context

_No response_

### LINKED ISSUE #6: Problems when installed alongside Particle Tweaks
### Describe the bug

Apparently, this was "fixed" in the particle tweaks changelog but whatever fix was implemented has done nothing and
the extra bubble pops still occur
image

### Steps to reproduce

1. install bubble pops 0.2.0
2. install particle tweaks 1.1.3
3. look at situations where bubble pops would usually appear
4. see that there's a second slightly out-of-sync bubble in the same place as the bubble

### Expected behavior

Simply just one bubble pop, this should not showcase two bubbles at weirdly offset times and in the same places

### Additional context

to be clear, while this was showcased in a quilt environment, I have tested and can confirm this appears alongside regular fabric.
also, I would have mentioned this to the particle tweaks issues, but there is no issues page linked and I couldn't find any similar way to contact the mod dev about this, so I'm just posting it here to see if you could fix it on your end

### LINKED ISSUE #8: Varied Bubble Pop Volume
### Is your suggested enhancement related to a problem? Please describe.

_No response_

### Describe the solution you'd like

It'd be nice if the sound effects for when a bubble pops had varied volume instead of all being at 0.1. Bubbles often generate in large quantities and them all popping at the same volume can be a bit annoying. In fact, maybe even some of them should make no sound at all.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### LINKED ISSUE #9: Magma block bubble column appears to pop inside the block rather than on the top
### Is your feature request related to a problem? Please describe.

Title. This isn't the fault of the mod, it also happens in vanilla (the bubbles blink out of existence halfway inside the block).

### Describe the feature you'd like

Either adjusting the bubbles' target Y if possible, or collision detection.

### Describe alternatives you've considered

_No response_

### Additional context

Using version 0.2.0 of the mod for Fabric on MC 1.20.4.

### LINKED ISSUE #11: Barrels opened by other players don't spawn bubbles
### Describe the bug

Opening chests or barrels creates bubbles. Watching another player open a chest, I see bubbles, but not with a barrel.

### Steps to reproduce

1. Be in multiplayer
2. Place barrel
3. Have friend click barrel

### Expected behavior

bubble

### Additional context

Using version 0.2.0 of the mod for Fabric on MC 1.20.4.

### LINKED ISSUE #12: Nitpick: Literal newline in `fabric.mod.json` of 0.2.0 artifact
This doesn't seem to be a problem for the Fabric loader, but a strict parser like `jq`'s will choke on literal newlines in strings.
Since it's not literal in the source:
https://github.com/Tschipcraft/make_bubbles_pop/blob/f23c11c4fcf519320bebc35fc4d2538122b73361/fabric/src/main/resources/fabric.mod.json#L6
...I'm guessing the process of expanding templates is what introduces it.

### LINKED ISSUE #13: 1.20.6 support
### Is your feature request related to a problem? Please describe.

The mod crashes when starting on 1.20.6

### Describe the feature you'd like

Add a 1.20.6 support to the mod

### Additional context

Crash log:
```
[11:07:35] [main/ERROR]: Mixin apply for mod make_bubbles_pop failed make_bubbles_pop.mixins.json:BarrelOnUse from mod make_bubbles_pop -> net.minecraft.class_3708: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on injectBubbles could not find any targets matching 'Lnet/minecraft/class_3708;method_9534(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;)Lnet/minecraft/class_1269;' in net.minecraft.class_3708. Using refmap make_bubbles_pop-refmap.json [PREINJECT Applicator Phase -> make_bubbles_pop.mixins.json:BarrelOnUse from mod make_bubbles_pop -> Prepare Injections ->  -> handler$dld000$make_bubbles_pop$injectBubbles(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on injectBubbles could not find any targets matching 'Lnet/minecraft/class_3708;method_9534(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;)Lnet/minecraft/class_1269;' in net.minecraft.class_3708. Using refmap make_bubbles_pop-refmap.json [PREINJECT Applicator Phase -> make_bubbles_pop.mixins.json:BarrelOnUse from mod make_bubbles_pop -> Prepare Injections ->  -> handler$dld000$make_bubbles_pop$injectBubbles(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) [?:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:336) [client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:53) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:170) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2024-05-12 11:07:37
Description: Bootstrap

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3708 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_2358.method_10199(class_2358.java:336)
	at net.minecraft.class_2966.method_12851(class_2966.java:53)
	at net.minecraft.client.main.Main.main(Main.java:170)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 13 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [make_bubbles_pop.mixins.json:BarrelOnUse from mod make_bubbles_pop] from phase [DEFAULT] in config [make_bubbles_pop.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 16 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on injectBubbles could not find any targets matching 'Lnet/minecraft/class_3708;method_9534(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;)Lnet/minecraft/class_1269;' in net.minecraft.class_3708. Using refmap make_bubbles_pop-refmap.json [PREINJECT Applicator Phase -> make_bubbles_pop.mixins.json:BarrelOnUse from mod make_bubbles_pop -> Prepare Injections ->  -> handler$dld000$make_bubbles_pop$injectBubbles(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_1657;Lnet/minecraft/class_1268;Lnet/minecraft/class_3965;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 16 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_2358.method_10199(class_2358.java:336)
	at net.minecraft.class_2966.method_12851(class_2966.java:53)
Mixins in Stacktrace:
	net.minecraft.class_2358:
		net.fabricmc.fabric.mixin.content.registry.FireBlockMixin (fabric-content-registries-v0.mixins.json)
	net.minecraft.class_2966:
		org.embeddedt.modernfix.common.mixin.feature.measure_time.BootstrapMixin (modernfix-common.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.BootstrapMixin (fabric-registry-sync-v0.mixins.json)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:170)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Mixins in Stacktrace: None found
```

### LINKED ISSUE #14: update to 1.20.6
### Is your feature request related to a problem? Please describe.

_No response_

### Describe the feature you'd like

just an update to 1.20.6 because this mod is cool

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### LINKED ISSUE #15: 1.21 Support
### Is your feature request related to a problem? Please describe.

No.

### Describe the feature you'd like

Mod needs updated to the latest version.

### Describe alternatives you've considered

N/A

### Additional context

Love the mod. Thanks!

### PR DESCRIPTION
**Pull request by AViewFromTheTop**
If anything else is needed or if you want me to try adding anything else, just let me know
I'm open to this PR being edited as well, it's just a basis for compat with Wilder Wild and Particle Tweaks

CURRENT CHANGES (edited by @Tschipcraft):
- **Support for Minecraft 1.21** ⚔️ (closes [#13](https://github.com/Tschipcraft/make_bubbles_pop/issues/13), [#14](https://github.com/Tschipcraft/make_bubbles_pop/issues/14), [#15](https://github.com/Tschipcraft/make_bubbles_pop/issues/15))
- **Added config file and settings menu when installed alongside [MidnightLib](https://modrinth.com/mod/midnightlib)** (closes [#4](https://github.com/Tschipcraft/make_bubbles_pop/issues/4))
- **Added entity interaction physics to bubbles** (configurable)
- **Added biome dependent tint to all bubble types** (configurable)
- **Fixed barrels opened by other players on servers not emitting bubbles** (closes [#11](https://github.com/Tschipcraft/make_bubbles_pop/issues/11)) (@AViewFromTheTop)
- Adjusted current down bubbles to pop on top of magma blocks rather than inside them (closes [#9](https://github.com/Tschipcraft/make_bubbles_pop/issues/9))
- Added varied pitch and volume to bubble pop and bubble swirl sounds (closes [#8](https://github.com/Tschipcraft/make_bubbles_pop/issues/8)) (@AViewFromTheTop)
- Barrel bubbling is now reliable on the client and will no longer bubble when a chunk with an already opened Barrel is loaded (@AViewFromTheTop)
- Fixed checking incorrect side of barrels for bubble particles
- Changed the default behavior to not maintain bubble particle velocity when popping (configurable) (@AViewFromTheTop)
- Tweaked explosion bubbles and used better variable names
- Restructured bubble particle logic and used better variable types
- Adjusted barrel bubble spawn locations
- Moved bubble pop logic to a separate utility class to reduce code duplication
- Simplified water checks to use the already provided helper function in world or level
- Fixed literal new line in fabric.mod.json after building (closes [#12](https://github.com/Tschipcraft/make_bubbles_pop/issues/12))

### CODE REVIEW

**Comment by AViewFromTheTop** [comment]
Just letting you know btw, Math.cos and Math.sin are ever so slightly faster than their MathHelper variants, even when they're casted to another variable
In this case the regular Math.cos/sin methods wouldn't even need to be casted so I just swapped them out

**Comment by Tschipcraft** [comment]
Hello, thank your for actually contributing to Make Bubbles Pop! 
For me university just started so I sadly have little to no free time available to check the pull request and make a new release at least the next few days

**Comment by Tschipcraft** [comment]
> Just letting you know btw, Math.cos and Math.sin are ever so slightly faster than their MathHelper variants, even when they're casted to another variable In this case the regular Math.cos/sin methods wouldn't even need to be casted so I just swapped them out

Thanks, I didn't know that

**Comment by AViewFromTheTop** [comment]
Yeah same here college kinda sucks

**Review by Tschipcraft — APPROVED** [review]

**Comment by AViewFromTheTop** [comment]
actually im gonna luna-fy the mod lol (or aviewfromthetop-ify)

**Comment by Tschipcraft** [comment]
ohh, nice!
I'm just going to use this pr as a base and add my own commits to it

**Comment by Tschipcraft** [comment]
Actually, I like the pop bubbles not retaining their velocity more as well... maybe I'll just ditch the option
Any idea how I could implement the custom network packet on Forge?

**Comment by AViewFromTheTop** [comment]
> Actually, I like the pop bubbles not retaining their velocity more as well... maybe I'll just ditch the option
> Any idea how I could implement the custom network packet on Forge?

I unfortunately know literally nothing about Forge other than how to register some things lol

**Comment by Tschipcraft** [comment]
Damn, rip

**Comment by AViewFromTheTop** [comment]
@Tschipcraft is it ok if I change the mod version to 1.20.1 and add FrozenLib+Cloth Config config compat to this?
FrozenLib allows for config syncing between client and server (modifiable with annotations) but we haven't released a version with that below 1.20.1.

Edit: I just remembered I only know how to do Fabric stuff

**Comment by Tschipcraft** [comment]
This approach would replace MidnightLib, correct? The reason I chose MidnightLib over Cloth Config (and any other config lib I found) was that it just seemed easier to implement and not having to worry about Minecraft specific library versions. Additionally, I'm not sure if client server sync is really necessary for a client only mod.. But I'm open to hear about benefits this might bring that I'm not aware of.

Because of the new commits, I'm not sure if a client folder for the mixins is necessary in its current state (because there are no server side mixins rn (and please use git move the next time so that GitHub shows that the file was moved in the diff view rather than removed and added)), I've not experienced any issues regarding chunk loading with barrel bubbles, but I guess this became necessary because of the openedBarrels clean up, and is there a specific reason you replaced a lot of variable assignments with an uppercase type indicator? (I like the lowercase one more /shrug) But thanks for the continuous help!

**Comment by AViewFromTheTop** [comment]
> This approach would replace MidnightLib, correct? The reason I chose MidnightLib over Cloth Config (and any other config lib I found) was that it just seemed easier to implement and not having to worry about Minecraft specific library versions. Additionally, I'm not sure if client server sync is really necessary for a client only mod.. But I'm open to hear about benefits this might bring that I'm not aware of.
> 
> Because of the new commits, I'm not sure if a client folder for the mixins is necessary in its current state (because there are no server side mixins rn (and please use git move the next time so that GitHub shows that the file was moved in the diff view rather than removed and added)), I've not experienced any issues regarding chunk loading with barrel bubbles, but I guess this became necessary because of the openedBarrels clean up, and is there a specific reason you replaced a lot of variable assignments with an uppercase type indicator? (I like the lowercase one more /shrug) But thanks for the continuous help!

The FrozenLib thing isn’t exactly necessary, but just an option since I use it (im part of FrozenBlock and don’t use many mods lol)
I wouldn’t want it to *replace* Midnight, but rather load as an alternative
As for the client-server syncing thing, it’s not exactly useful for this mod unless you want all players to have the same experience or don’t want them changing a specific config without having to relog (there are three modes of config syncing- sync to server (requires op,) can only be updated outside server and doesn’t sync (or updatable with op perms,) and modifyable and unsinkable for the client.)

**Comment by AViewFromTheTop** [comment]
The client folder was done because the Minecraft Development Plugin (which helps a TON with mixins) puts mixins into the general category instead of client without that extra folder
As for the variable stuff, it’s just my personal preference and it’s easier for me to read
I don’t mind if you revert it since it doesn’t really impact anything lol

**Comment by AViewFromTheTop** [comment]
Also, the chunk loading issue is easily replicable by simply relogging in front of a barrel that you’ve changed to open with a Debug Stick. This behavior would be noticeable to people who are in multiplayer so I decided to fix it.

**Comment by Tschipcraft** [comment]
> The client folder was done because the Minecraft Development Plugin (which helps a TON with mixins) puts mixins into the general category instead of client without that extra folder As for the variable stuff, it’s just my personal preference and it’s easier for me to read I don’t mind if you revert it since it doesn’t really impact anything lol

Ah, I see. I'm using that plugin as well, but I didn't know that it distinguishes mixins like that, thanks!

**Comment by Tschipcraft** [comment]
> Also, the chunk loading issue is easily replicable by simply relogging in front of a barrel that you’ve changed to open with a Debug Stick. This behavior would be noticeable to people who are in multiplayer so I decided to fix it.

Oh, so that happened when joining a server, that makes sense. I was out here trying to replicate it with F3+A to reload all chunk and be like I don't see it lmao

**Comment by Tschipcraft** [comment]
> The FrozenLib thing isn’t exactly necessary, but just an option since I use it (im part of FrozenBlock and don’t use many mods lol) I wouldn’t want it to _replace_ Midnight, but rather load as an alternative As for the client-server syncing thing, it’s not exactly useful for this mod unless you want all players to have the same experience or don’t want them changing a specific config without having to relog (there are three modes of config syncing- sync to server (requires op,) can only be updated outside server and doesn’t sync (or updatable with op perms,) and modifyable and unsinkable for the client.)

If that works ontop of MidnightLib or in parallel, I might consider it. Additional compatibility doesn't sound bad, if it's not that hard to implement and maintain.. Could you send me a link to e.g. a different project where this is implemented, so I can take a look at how it looks with the annotations?
I hope it's understandable, that I'm pretty careful about greenlighting changes like this, because I don't want to end up in some sort of dependency hell where I have to publish new versions and make changes for just the dependencies to work e.g. for new mc versions.

**Comment by AViewFromTheTop** [comment]
> If that works ontop of MidnightLib or in parallel, I might consider it. Additional compatibility doesn't sound bad, if it's not that hard to implement and maintain.. Could you send me a link to e.g. a different project where this is implemented, so I can take a look at how it looks with the annotations? I hope it's understandable, that I'm pretty careful about greenlighting changes like this, because I don't want to end up in some sort of dependency hell where I have to publish new versions and make changes for just the dependencies to work e.g. for new mc versions.

I don’t anticipate us changing our config stuff at all unless Cloth itself changes, which I guess is just as likely as MidnightLib changing lol
I’d probably give FLIB priority if it and cloth are installed if so, and midnight if not (unless you want it the other way around lol)

Me and my team’s magnum opus wilder wild uses the config stuff btw
https://github.com/FrozenBlock/WilderWild/tree/master/src/main/java/net/frozenblock/wilderwild/config

**Comment by Tschipcraft** [comment]
Damn, Wilder Wild actually looks pretty epic, very nice.
All right, I'll let you cook. If you wouldn't embed FLIB, wouldn't that solve the problem with the annotation features not being available below 1.20.1 btw?

Also, if you happen to make a commit before me, do me a favor and remove `cache-write-only: true` in https://github.com/AViewFromTheTop/make_bubbles_pop/blob/master/.github/workflows/build.yml so that the workflow hopefully uses the cache (I added that in my last commit)

**Comment by AViewFromTheTop** [comment]
Actually, once I get around to adding the FLib stuff, I'm going to make it take priority.
Simple reason: I forgot Treetrain also added Config Modifications, so theoretically Wilder Wild can set Make Bubbles Pop's Chest Bubbling to false and properly override it with its behavior!

**Comment by AViewFromTheTop** [comment]
Also, not embedding FLib would still cause issues for builds below 1.20.1 since anyone who happens to be using one of our mods (which rely on FrozenLib) will absolutely experience a crash.
I'm probably just going to have to make a separate branch for 1.20.1+ updates.

**Comment by Tschipcraft** [comment]
> Also, not embedding FLib would still cause issues for builds below 1.20.1 since anyone who happens to be using one of our mods (which rely on FrozenLib) will absolutely experience a crash. I'm probably just going to have to make a separate branch for 1.20.1+ updates.

Why though? If the mod checks for FLib and e.g. a Minecraft version above or equal 1.20.1 before initializing the config class for FLib (and therefore call the library) it should work fine? If it doesn't call the problematic code, it doesn't crash, unless FLib itself calls some parts of it somehow even when it's not registered

**Comment by Tschipcraft** [comment]
> Actually, once I get around to adding the FLib stuff, I'm going to make it take priority. Simple reason: I forgot Treetrain also added Config Modifications, so theoretically Wilder Wild can set Make Bubbles Pop's Chest Bubbling to false and properly override it with its behavior!

Wilder Wild has chest bubbling? Damn rip my features 🫠

**Comment by AViewFromTheTop** [comment]
> Why though? If the mod checks for FLib and e.g. a Minecraft version above or equal 1.20.1 before initializing the config class for FLib (and therefore call the library) it should work fine? If it doesn't call the problematic code, it doesn't crash, unless FLib itself calls some parts of it somehow even when it's not registered

That should work, I kinda forgot you could call for the MC version-

**Comment by AViewFromTheTop** [comment]
> Wilder Wild has chest bubbling? Damn rip my features 🫠

I found out about Make Bubbles Pop a couple months after I added it lmao
it doesn't have all the other bubble stuff though

**Comment by Tschipcraft** [comment]
> I found out about Make Bubbles Pop a couple months after I added it lmao it doesn't have all the other bubble stuff though

Ah well, it's a pretty common idea, Effective also added chest bubbling after myself a while ago

**Comment by Tschipcraft** [comment]
Btw, any particular reasons why you switched from storing block positions to block entities in the array list in the barrel bubbles, and why from an override to an inject that cancels the method in BubblePop, wouldn't a redirect be better if overrides should be avoided?

**Comment by AViewFromTheTop** [comment]
> Btw, any particular reasons why you switched from storing block positions to block entities in the array list in the barrel bubbles, and why from an override to an inject that cancels the method in BubblePop, wouldn't a redirect be better if overrides should be avoided?

It prevents block entities from other dimensions potentially bubbling (though im not 100% but it’s just to be safe)
As for the redirect, that can cause mod compat issues
Simply injecting and canceling does the same but saves you from dealing with potential issues with other mods

**Comment by Tschipcraft** [comment]
I tested this out a bit, saving only the BlockPos does prevent containers in other dimensions in the same location to bubble, at least from my testing. I'm gonna change this back to be consistent with the Forge version, solely because saving the BlockPos there is easier lol

**Comment by R00tB33rMan** [comment]
This weirdly fixes 1.20.5/6 support. Cannot identify any bugs since the latest changes you've made 3 months ago with a performance-based modpack.

**Comment by Tschipcraft** [comment]
I mean yeah, v0.3.0 is basically done. I just need to backport it to pre 1.19.4 versions still. I'll have time in approx. 1 month when the semester ends

**Comment by Vi-Tul** [comment]
Works fine even in 1.21 version

**Comment by AViewFromTheTop** [comment]
My apologies for not contributing for a while, life got in the way and I’ve been working on lots of bugfixes for Wilder Wild.
Once I get Particle Tweaks on 1.21 I’ll try to see what I can do here, if anything
It just kinda sucks that I don’t know forge

**Comment by Tschipcraft** [comment]
Ya, no worries. I know the feeling. I want to push out v0.3.0 in the next few weeks before any new features, since it's been almost a year since the last update, but after that I'd still be interested in the FLib integration (and/or any other additions/fixes). Oh and again thanks for contributing in the first place <3

**Comment by Tschipcraft** [comment]
> Works fine even in 1.21 version

Forge version sadly doesn't work in 1.21 yet

_Edit:_ Works now

**Pull request merged**
